name: gdg_dsgn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  husky: ^0.1.7

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Thin.otf
          weight: 100
        - asset: fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: fonts/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard-Black.otf
          weight: 900
