name: Deploy Flutter Web to GitHub Pages

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1

      - name: Install dependencies
        working-directory: widgetbook
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: widgetbook
        run: flutter build web --base-href="/GDG-KUDS-Flutter/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: widgetbook/build/web
